# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1030, 655)
        self.Main_GIF = QtWidgets.QLabel(Widget)
        self.Main_GIF.setGeometry(QtCore.QRect(6, 2, 1031, 681))
        self.Main_GIF.setText("")
        self.Main_GIF.setPixmap(QtGui.QPixmap("Data/main_gif.gif"))
        self.Main_GIF.setScaledContents(True)
        self.Main_GIF.setWordWrap(False)
        self.Main_GIF.setObjectName("Main_GIF")
        self.RUN_Button = QtWidgets.QPushButton(Widget)
        self.RUN_Button.setGeometry(QtCore.QRect(750, 550, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RUN_Button.setFont(font)
        self.RUN_Button.setAutoFillBackground(False)
        self.RUN_Button.setStyleSheet("background-color: rgb(239, 239, 0);")
        self.RUN_Button.setObjectName("RUN_Button")
        self.Exit_Button = QtWidgets.QPushButton(Widget)
        self.Exit_Button.setGeometry(QtCore.QRect(840, 550, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Exit_Button.setFont(font)
        self.Exit_Button.setAutoFillBackground(False)
        self.Exit_Button.setStyleSheet("background-color: rgb(97, 194, 0);")
        self.Exit_Button.setObjectName("Exit_Button")
        self.Init_System = QtWidgets.QLabel(Widget)
        self.Init_System.setGeometry(QtCore.QRect(10, 10, 401, 131))
        self.Init_System.setText("")
        self.Init_System.setPixmap(QtGui.QPixmap("Data/init_system.gif"))
        self.Init_System.setScaledContents(False)
        self.Init_System.setObjectName("Init_System")
        self.Date = QtWidgets.QTextBrowser(Widget)
        self.Date.setGeometry(QtCore.QRect(570, 20, 225, 120))
        self.Date.setObjectName("Date")
        self.Date.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:cyan;\n"
        "font-size:20px;")
        self.Time = QtWidgets.QTextBrowser(Widget)
        self.Time.setGeometry(QtCore.QRect(800, 20, 225, 120))
        self.Time.setObjectName("Time")
        self.Time.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:cyan;\n"
        "font-size:20px;")
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.RUN_Button.setText(_translate("Widget", "RUN"))
        self.Exit_Button.setText(_translate("Widget", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
